dwa_planner:
  ros__parameters:
    # kinematic: [max_vel, max_omega_deg, accel, accel_omega_deg, v_reso, w_reso_deg]
    kinematic: [0.5, 20.0, 0.1, 50.0, 0.01, 1.0]
    # eval_param: [heading_gain, dist_gain, vel_gain, predict_dt]
    eval_param: [0.1, 0.1, 0.1, 3.0]
    # 半径
    robot_radius: 0.3
    obstacle_radius: 0.3