name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/unit_test
  pull_request:
    branches:
      - main
      - develop
      - feature/unit_test

jobs:
  build-and-test:
    container: osrf/ros:humble-ros-base
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install development tools & dependencies
        run: |
          apt-get update
          apt-get install -y \
            python3-colcon-common-extensions \
            python3-rosdep \
            lcov
          rosdep init || true
          rosdep update

      - name: Install ROS package dependencies
        run: |
          source /opt/ros/humble/setup.bash
          rosdep install --from-paths src --ignore-src --rosdistro humble -r -y

      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build \
            --packages-select dwa_planner \
            --cmake-args -DCMAKE_CXX_FLAGS="--coverage"

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test \
            --packages-select dwa_planner \
            --event-handlers console_direct+ \
            --ctest-args -R test_dwa_all_functions
