name: CI

on:
  push:
    branches:
      - main
<<<<<<< HEAD
      - develop
=======
>>>>>>> origin/develop
      - feature/unit_test
  pull_request:
    branches:
      - main
<<<<<<< HEAD
      - develop
=======
>>>>>>> origin/develop
      - feature/unit_test

jobs:
  build-and-test:
<<<<<<< HEAD

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ROS2 Humble
        run: |
          sudo apt update && sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-rosdep
          sudo rosdep init || true
          rosdep update
        
=======
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: humble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ROS 2 Humble
        uses: ros-tooling/setup-ros@v0.1
        with:
          version: ${{ env.ROS_DISTRO }}

>>>>>>> origin/develop
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-colcon-common-extensions lcov

      - name: Install ROS package dependencies
        run: |
<<<<<<< HEAD
          source /opt/ros/humble/setup.bash
=======
          source /opt/ros/${ROS_DISTRO}/setup.bash
>>>>>>> origin/develop
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        run: |
<<<<<<< HEAD
          source /opt/ros/humble/setup.bash
=======
          source /opt/ros/${ROS_DISTRO}/setup.bash
>>>>>>> origin/develop
          colcon build \
            --packages-select dwa_planner \
            --cmake-args -DCMAKE_CXX_FLAGS="--coverage"

      - name: Run tests
        run: |
<<<<<<< HEAD
          source /opt/ros/humble/setup.bash
=======
          source install/setup.bash
>>>>>>> origin/develop
          colcon test \
            --packages-select dwa_planner \
            --event-handlers console_direct+ \
            --ctest-args -R test_dwa_all_functions
